version: "3.7"

services: 
  database: 
    image: postgres
    container_name: "database"
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=bycoders
    volumes: 
      - pgdata:/data/postgres
    networks:
      - app-network
      
  app:
    build: .
    container_name: bycoders
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


volumes: 
  pgdata:
    driver: local